### ISSUE TITLE
Coalition Update Mod incompatible with 2.5

### ISSUE THREAD

**Issue by andreyzh** [mrSkortch/DCS-miscScripts#1]
@mrSkortch 
Hi Grimes / uboats,

I noticed that there are some problems in using the mod with DCS 2.5 - the mission editor won't open.
I did a quick diff of the files using the WinMerge, and the change was quite trivial. 

Attaching the result here so that you can update the source if you wish.

-Andrei.
[MissionEditor.zip](https://github.com/mrSkortch/DCS-miscScripts/files/1678681/MissionEditor.zip)

**Comment by mrSkortch** [comment]
Thanks for taking the time to fix it for me. 

Merged it.
